// ============================================================
// Real Zero Trust controls — auto-generated from
// cloud-compliance-automation/policies/Policy_Catalog_Architecture.yaml
// Total: 98 controls (HIPAA TC-*, SeHE SC-*, CCC CCC-*)
// ============================================================

export type Pillar =
  | "Identity"
  | "Devices"
  | "Networks"
  | "Data"
  | "Visibility & Analytics"
  | "Applications and Workloads";

export type Severity = "critical" | "high" | "medium" | "low";
export type Standard = "CCC" | "HIPAA" | "SeHE";
export type ControlStatus = "pass" | "fail" | "skipped" | "error";

export interface Control {
  id: string;           // e.g. "TC-01"
  pillar: Pillar;
  severity: Severity;
  standards: Standard[];
  title: string;
  description: string;
  evidenceSource: string[];
  remediationGuidance: string;
}

export interface ControlResult extends Control {
  status: ControlStatus;
  violations: string[];
}

export const CONTROLS: Control[] = [
  { id: "TC-01", pillar: "Identity", severity: "critical", standards: ["HIPAA", "CCC"], title: "§164.312(a)(1) – Access Control", description: "Compliance control: §164.312(a)(1) – Access Control", evidenceSource: ["Access Logs / Audit Trails"], remediationGuidance: "Review and remediate §164.312(a)(1) – Access Control. See: §164.312(a)(1) – Access Control" },
  { id: "TC-02", pillar: "Identity", severity: "critical", standards: ["HIPAA", "CCC"], title: "§164.312(a)(2)(ii) – Emergency Access Procedure", description: "Compliance control: §164.312(a)(2)(ii) – Emergency Access Procedure", evidenceSource: ["System Configuration"], remediationGuidance: "Review and remediate §164.312(a)(2)(ii) – Emergency Access Procedure. See: §164.312(a)(2)(ii) – Emergency Access Procedure" },
  { id: "TC-03", pillar: "Identity", severity: "high", standards: ["HIPAA", "CCC"], title: "§164.312(a)(2)(iii) – Automatic Logoff", description: "Compliance control: §164.312(a)(2)(iii) – Automatic Logoff", evidenceSource: ["Session Logs"], remediationGuidance: "Review and remediate §164.312(a)(2)(iii) – Automatic Logoff. See: §164.312(a)(2)(iii) – Automatic Logoff" },
  { id: "TC-04", pillar: "Identity", severity: "critical", standards: ["HIPAA", "CCC"], title: "§164.312(a)(2)(iv) – Encryption and Decryption", description: "Compliance control: §164.312(a)(2)(iv) – Encryption and Decryption", evidenceSource: ["Cloud Provider Config"], remediationGuidance: "Review and remediate §164.312(a)(2)(iv) – Encryption and Decryption. See: §164.312(a)(2)(iv) – Encryption and Decryption" },
  { id: "TC-05", pillar: "Visibility & Analytics", severity: "high", standards: ["HIPAA", "CCC"], title: "§164.312(b) – Audit Controls (Logging Enabled)", description: "Compliance control: §164.312(b) – Audit Controls (Logging Enabled)", evidenceSource: ["Cloud Provider Config / OS Config"], remediationGuidance: "Review and remediate §164.312(b) – Audit Controls (Logging Enabled). See: §164.312(b) – Audit Controls (Logging Enabled)" },
  { id: "TC-06", pillar: "Visibility & Analytics", severity: "high", standards: ["HIPAA", "CCC"], title: "§164.312(b) – Audit Controls (ePHI Actions Logged)", description: "Compliance control: §164.312(b) – Audit Controls (ePHI Actions Logged)", evidenceSource: ["Application Logs / DB Logs"], remediationGuidance: "Review and remediate §164.312(b) – Audit Controls (ePHI Actions Logged). See: §164.312(b) – Audit Controls (ePHI Actions Logged)" },
  { id: "TC-07", pillar: "Visibility & Analytics", severity: "high", standards: ["HIPAA", "CCC"], title: "§164.312(b) – Audit Controls (Admin Actions Logged)", description: "Compliance control: §164.312(b) – Audit Controls (Admin Actions Logged)", evidenceSource: ["Audit Trails / CloudTrail"], remediationGuidance: "Review and remediate §164.312(b) – Audit Controls (Admin Actions Logged). See: §164.312(b) – Audit Controls (Admin Actions Logged)" },
  { id: "TC-08", pillar: "Visibility & Analytics", severity: "medium", standards: ["HIPAA", "CCC"], title: "§164.312(b) – Audit Controls (Record Access Logged)", description: "Compliance control: §164.312(b) – Audit Controls (Record Access Logged)", evidenceSource: ["Application Logs / DB Logs"], remediationGuidance: "Review and remediate §164.312(b) – Audit Controls (Record Access Logged). See: §164.312(b) – Audit Controls (Record Access Logged)" },
  { id: "TC-09", pillar: "Data", severity: "critical", standards: ["HIPAA", "CCC"], title: "§164.312(c)(1) – Integrity", description: "Compliance control: §164.312(c)(1) – Integrity", evidenceSource: ["Data Integrity Monitoring Tools"], remediationGuidance: "Review and remediate §164.312(c)(1) – Integrity. See: §164.312(c)(1) – Integrity" },
  { id: "TC-10", pillar: "Data", severity: "critical", standards: ["HIPAA", "CCC"], title: "§164.312(c)(2) – Mechanism to Authenticate ePHI", description: "Compliance control: §164.312(c)(2) – Mechanism to Authenticate ePHI", evidenceSource: ["Application Logic / Runtime Logs"], remediationGuidance: "Review and remediate §164.312(c)(2) – Mechanism to Authenticate ePHI. See: §164.312(c)(2) – Mechanism to Authenticate ePHI" },
  { id: "TC-11", pillar: "Data", severity: "critical", standards: ["HIPAA", "CCC"], title: "§164.312(d) – Person or Entity Authentication", description: "Compliance control: §164.312(d) – Person or Entity Authentication", evidenceSource: ["Access Logs / API Gateway Logs"], remediationGuidance: "Review and remediate §164.312(d) – Person or Entity Authentication. See: §164.312(d) – Person or Entity Authentication" },
  { id: "TC-12", pillar: "Data", severity: "critical", standards: ["HIPAA", "CCC"], title: "§164.312(e)(1) – Transmission Security", description: "Compliance control: §164.312(e)(1) – Transmission Security", evidenceSource: ["VPC Flow Logs / Network Traffic Analysis"], remediationGuidance: "Review and remediate §164.312(e)(1) – Transmission Security. See: §164.312(e)(1) – Transmission Security" },
  { id: "TC-13", pillar: "Data", severity: "high", standards: ["HIPAA", "CCC"], title: "§164.312(e)(2)(i) – Integrity Controls", description: "Compliance control: §164.312(e)(2)(i) – Integrity Controls", evidenceSource: ["Network Traffic Analysis"], remediationGuidance: "Review and remediate §164.312(e)(2)(i) – Integrity Controls. See: §164.312(e)(2)(i) – Integrity Controls" },
  { id: "TC-14", pillar: "Data", severity: "critical", standards: ["HIPAA", "CCC"], title: "§164.312(e)(2)(ii) – Encryption", description: "Compliance control: §164.312(e)(2)(ii) – Encryption", evidenceSource: ["VPC Flow Logs / Network Traffic Analysis"], remediationGuidance: "Review and remediate §164.312(e)(2)(ii) – Encryption. See: §164.312(e)(2)(ii) – Encryption" },
  { id: "SC-01", pillar: "Identity", severity: "medium", standards: ["SeHE", "CCC"], title: "Information Security Policy – §4.3", description: "Compliance control: Information Security Policy – §4.3", evidenceSource: ["Cloud Provider Config / System Config"], remediationGuidance: "Review and remediate Information Security Policy – §4.3. See: Information Security Policy – §4.3" },
  { id: "SC-02", pillar: "Identity", severity: "medium", standards: ["SeHE", "CCC"], title: "Information Security Policy – §4.3", description: "Compliance control: Information Security Policy – §4.3", evidenceSource: ["Session Logs / App Config"], remediationGuidance: "Review and remediate Information Security Policy – §4.3. See: Information Security Policy – §4.3" },
  { id: "SC-03", pillar: "Identity", severity: "medium", standards: ["SeHE", "CCC"], title: "Information Security Policy – §4.3", description: "Compliance control: Information Security Policy – §4.3", evidenceSource: ["Cloud Provider Config / OS Config"], remediationGuidance: "Review and remediate Information Security Policy – §4.3. See: Information Security Policy – §4.3" },
  { id: "SC-04", pillar: "Identity", severity: "medium", standards: ["SeHE", "CCC"], title: "Information Security Policy – §4.3", description: "Compliance control: Information Security Policy – §4.3", evidenceSource: ["Audit Logs / Application Logs"], remediationGuidance: "Review and remediate Information Security Policy – §4.3. See: Information Security Policy – §4.3" },
  { id: "SC-05", pillar: "Identity", severity: "medium", standards: ["SeHE", "CCC"], title: "Information Security Policy – §4.3", description: "Compliance control: Information Security Policy – §4.3", evidenceSource: ["Storage Config / DB Config"], remediationGuidance: "Review and remediate Information Security Policy – §4.3. See: Information Security Policy – §4.3" },
  { id: "SC-06", pillar: "Identity", severity: "medium", standards: ["SeHE", "CCC"], title: "Information Security Policy – §4.3", description: "Compliance control: Information Security Policy – §4.3", evidenceSource: ["Network Traffic Analysis"], remediationGuidance: "Review and remediate Information Security Policy – §4.3. See: Information Security Policy – §4.3" },
  { id: "SC-07", pillar: "Identity", severity: "medium", standards: ["SeHE", "CCC"], title: "Information Security Policy – §4.3", description: "Compliance control: Information Security Policy – §4.3", evidenceSource: ["Cloud Provider Config / Network Config"], remediationGuidance: "Review and remediate Information Security Policy – §4.3. See: Information Security Policy – §4.3" },
  { id: "SC-08", pillar: "Identity", severity: "critical", standards: ["SeHE", "CCC"], title: "Authentication Policy – §7.3", description: "Compliance control: Authentication Policy – §7.3", evidenceSource: ["Audit Logs"], remediationGuidance: "Review and remediate Authentication Policy – §7.3. See: Authentication Policy – §7.3" },
  { id: "SC-09", pillar: "Identity", severity: "high", standards: ["SeHE", "CCC"], title: "Authentication Policy – §7.3", description: "Compliance control: Authentication Policy – §7.3", evidenceSource: ["Session Logs"], remediationGuidance: "Review and remediate Authentication Policy – §7.3. See: Authentication Policy – §7.3" },
  { id: "SC-10", pillar: "Identity", severity: "high", standards: ["SeHE", "CCC"], title: "Authentication Policy – §7.3", description: "Compliance control: Authentication Policy – §7.3", evidenceSource: ["Network Traffic Analysis / Connection Logs"], remediationGuidance: "Review and remediate Authentication Policy – §7.3. See: Authentication Policy – §7.3" },
  { id: "SC-11", pillar: "Identity", severity: "high", standards: ["SeHE", "CCC"], title: "Authentication Policy – §7.3", description: "Compliance control: Authentication Policy – §7.3", evidenceSource: ["Authentication Logs / IdP Logs"], remediationGuidance: "Review and remediate Authentication Policy – §7.3. See: Authentication Policy – §7.3" },
  { id: "SC-12", pillar: "Identity", severity: "high", standards: ["SeHE", "CCC"], title: "Authentication Policy – §7.3", description: "Compliance control: Authentication Policy – §7.3", evidenceSource: ["Access Logs"], remediationGuidance: "Review and remediate Authentication Policy – §7.3. See: Authentication Policy – §7.3" },
  { id: "SC-13", pillar: "Networks", severity: "critical", standards: ["SeHE", "CCC"], title: "Authentication Policy – §7.3", description: "Compliance control: Authentication Policy – §7.3", evidenceSource: ["Authentication Logs"], remediationGuidance: "Review and remediate Authentication Policy – §7.3. See: Authentication Policy – §7.3" },
  { id: "SC-14", pillar: "Networks", severity: "medium", standards: ["SeHE", "CCC"], title: "Audit Policy – §9.3", description: "Compliance control: Audit Policy – §9.3", evidenceSource: ["System Configuration"], remediationGuidance: "Review and remediate Audit Policy – §9.3. See: Audit Policy – §9.3" },
  { id: "SC-15", pillar: "Visibility & Analytics", severity: "medium", standards: ["SeHE", "CCC"], title: "Audit Policy – §9.3", description: "Compliance control: Audit Policy – §9.3", evidenceSource: ["Audit Logs"], remediationGuidance: "Review and remediate Audit Policy – §9.3. See: Audit Policy – §9.3" },
  { id: "SC-16", pillar: "Visibility & Analytics", severity: "medium", standards: ["SeHE", "CCC"], title: "Audit Policy – §9.3", description: "Compliance control: Audit Policy – §9.3", evidenceSource: ["Log Management System"], remediationGuidance: "Review and remediate Audit Policy – §9.3. See: Audit Policy – §9.3" },
  { id: "SC-17", pillar: "Visibility & Analytics", severity: "medium", standards: ["SeHE", "CCC"], title: "Audit Policy – §9.3", description: "Compliance control: Audit Policy – §9.3", evidenceSource: ["Audit Logs"], remediationGuidance: "Review and remediate Audit Policy – §9.3. See: Audit Policy – §9.3" },
  { id: "SC-18", pillar: "Visibility & Analytics", severity: "high", standards: ["SeHE", "CCC"], title: "Identity Management Policy – §6.3", description: "Compliance control: Identity Management Policy – §6.3", evidenceSource: ["HR System / Identity Provider"], remediationGuidance: "Review and remediate Identity Management Policy – §6.3. See: Identity Management Policy – §6.3" },
  { id: "SC-19", pillar: "Visibility & Analytics", severity: "high", standards: ["SeHE", "CCC"], title: "Identity Management Policy – §6.3", description: "Compliance control: Identity Management Policy – §6.3", evidenceSource: ["HR System / Identity Provider"], remediationGuidance: "Review and remediate Identity Management Policy – §6.3. See: Identity Management Policy – §6.3" },
  { id: "SC-20", pillar: "Visibility & Analytics", severity: "high", standards: ["SeHE", "CCC"], title: "Consent and Access Control Policy – §8.3", description: "Compliance control: Consent and Access Control Policy – §8.3", evidenceSource: ["Access Control System / API Gateway"], remediationGuidance: "Review and remediate Consent and Access Control Policy – §8.3. See: Consent and Access Control Policy – §8.3" },
  { id: "SC-21", pillar: "Visibility & Analytics", severity: "high", standards: ["SeHE", "CCC"], title: "Consent and Access Control Policy – §8.3", description: "Compliance control: Consent and Access Control Policy – §8.3", evidenceSource: ["Data Classification Scanners"], remediationGuidance: "Review and remediate Consent and Access Control Policy – §8.3. See: Consent and Access Control Policy – §8.3" },
  { id: "SC-22", pillar: "Visibility & Analytics", severity: "medium", standards: ["SeHE", "CCC"], title: "Consent and Access Control Policy – §8.3", description: "Compliance control: Consent and Access Control Policy – §8.3", evidenceSource: ["Access Logs / Consent Registry"], remediationGuidance: "Review and remediate Consent and Access Control Policy – §8.3. See: Consent and Access Control Policy – §8.3" },
  { id: "SC-23", pillar: "Visibility & Analytics", severity: "high", standards: ["SeHE", "CCC"], title: "Breach Notification Policy – §10.3", description: "Compliance control: Breach Notification Policy – §10.3", evidenceSource: ["SIEM / Anomaly Detection System"], remediationGuidance: "Review and remediate Breach Notification Policy – §10.3. See: Breach Notification Policy – §10.3" },
  { id: "SC-24", pillar: "Visibility & Analytics", severity: "high", standards: ["SeHE", "CCC"], title: "Breach Notification Policy – §10.3", description: "Compliance control: Breach Notification Policy – §10.3", evidenceSource: ["Ticketing System / Email Logs"], remediationGuidance: "Review and remediate Breach Notification Policy – §10.3. See: Breach Notification Policy – §10.3" },
  { id: "CCC-01", pillar: "Applications and Workloads", severity: "medium", standards: ["CCC"], title: "2-1 Asset Management", description: "Compliance control: 2-1 Asset Management", evidenceSource: ["CMDB / Cloud Provider APIs"], remediationGuidance: "Review and remediate 2-1 Asset Management. See: 2-1 Asset Management" },
  { id: "CCC-02", pillar: "Devices", severity: "medium", standards: ["CCC"], title: "2-1 Asset Management", description: "Compliance control: 2-1 Asset Management", evidenceSource: ["CMDB"], remediationGuidance: "Review and remediate 2-1 Asset Management. See: 2-1 Asset Management" },
  { id: "CCC-03", pillar: "Identity", severity: "critical", standards: ["CCC"], title: "2-2 Identity and Access Management", description: "Compliance control: 2-2 Identity and Access Management", evidenceSource: ["Audit Logs"], remediationGuidance: "Review and remediate 2-2 Identity and Access Management. See: 2-2 Identity and Access Management" },
  { id: "CCC-04", pillar: "Identity", severity: "critical", standards: ["CCC"], title: "2-2 Identity and Access Management", description: "Compliance control: 2-2 Identity and Access Management", evidenceSource: ["Authentication Logs / IdP Logs"], remediationGuidance: "Review and remediate 2-2 Identity and Access Management. See: 2-2 Identity and Access Management" },
  { id: "CCC-05", pillar: "Identity", severity: "critical", standards: ["CCC"], title: "2-2 Identity and Access Management", description: "Compliance control: 2-2 Identity and Access Management", evidenceSource: ["Cloud Provider IAM Config"], remediationGuidance: "Review and remediate 2-2 Identity and Access Management. See: 2-2 Identity and Access Management" },
  { id: "CCC-06", pillar: "Identity", severity: "high", standards: ["CCC"], title: "2-2 Identity and Access Management", description: "Compliance control: 2-2 Identity and Access Management", evidenceSource: ["App / System Config"], remediationGuidance: "Review and remediate 2-2 Identity and Access Management. See: 2-2 Identity and Access Management" },
  { id: "CCC-07", pillar: "Identity", severity: "high", standards: ["CCC"], title: "2-2 Identity and Access Management", description: "Compliance control: 2-2 Identity and Access Management", evidenceSource: ["Authentication Logs"], remediationGuidance: "Review and remediate 2-2 Identity and Access Management. See: 2-2 Identity and Access Management" },
  { id: "CCC-08", pillar: "Identity", severity: "high", standards: ["CCC"], title: "2-2 Identity and Access Management", description: "Compliance control: 2-2 Identity and Access Management", evidenceSource: ["Network Security Group / Firewall Rules"], remediationGuidance: "Review and remediate 2-2 Identity and Access Management. See: 2-2 Identity and Access Management" },
  { id: "CCC-09", pillar: "Devices", severity: "medium", standards: ["CCC"], title: "2-3 Information System Protection", description: "Compliance control: 2-3 Information System Protection", evidenceSource: ["Cloud Provider Config / Deployment Scripts"], remediationGuidance: "Review and remediate 2-3 Information System Protection. See: 2-3 Information System Protection" },
  { id: "CCC-10", pillar: "Devices", severity: "medium", standards: ["CCC"], title: "2-3 Information System Protection", description: "Compliance control: 2-3 Information System Protection", evidenceSource: ["Vulnerability Scanners / Agent State Reports"], remediationGuidance: "Review and remediate 2-3 Information System Protection. See: 2-3 Information System Protection" },
  { id: "CCC-11", pillar: "Devices", severity: "medium", standards: ["CCC"], title: "2-3 Information System Protection", description: "Compliance control: 2-3 Information System Protection", evidenceSource: ["VPC Config / IAM Policies / NSG"], remediationGuidance: "Review and remediate 2-3 Information System Protection. See: 2-3 Information System Protection" },
  { id: "CCC-12", pillar: "Devices", severity: "medium", standards: ["CCC"], title: "2-3 Information System Protection", description: "Compliance control: 2-3 Information System Protection", evidenceSource: ["File Integrity Monitoring Logs"], remediationGuidance: "Review and remediate 2-3 Information System Protection. See: 2-3 Information System Protection" },
  { id: "CCC-13", pillar: "Data", severity: "critical", standards: ["CCC"], title: "2-4 Networks Security Management", description: "Compliance control: 2-4 Networks Security Management", evidenceSource: ["Cloud Provider Network Config"], remediationGuidance: "Review and remediate 2-4 Networks Security Management. See: 2-4 Networks Security Management" },
  { id: "CCC-14", pillar: "Data", severity: "critical", standards: ["CCC"], title: "2-4 Networks Security Management", description: "Compliance control: 2-4 Networks Security Management", evidenceSource: ["Cloud Provider Network Config"], remediationGuidance: "Review and remediate 2-4 Networks Security Management. See: 2-4 Networks Security Management" },
  { id: "CCC-15", pillar: "Data", severity: "high", standards: ["CCC"], title: "2-4 Networks Security Management", description: "Compliance control: 2-4 Networks Security Management", evidenceSource: ["Cloud Provider Network Config"], remediationGuidance: "Review and remediate 2-4 Networks Security Management. See: 2-4 Networks Security Management" },
  { id: "CCC-16", pillar: "Data", severity: "high", standards: ["CCC"], title: "2-4 Networks Security Management", description: "Compliance control: 2-4 Networks Security Management", evidenceSource: ["Cloud Provider Config"], remediationGuidance: "Review and remediate 2-4 Networks Security Management. See: 2-4 Networks Security Management" },
  { id: "CCC-17", pillar: "Data", severity: "high", standards: ["CCC"], title: "2-4 Networks Security Management", description: "Compliance control: 2-4 Networks Security Management", evidenceSource: ["VPC Config / Routing Tables"], remediationGuidance: "Review and remediate 2-4 Networks Security Management. See: 2-4 Networks Security Management" },
  { id: "CCC-18", pillar: "Applications and Workloads", severity: "medium", standards: ["CCC"], title: "2-5 Mobile Devices Security", description: "Compliance control: 2-5 Mobile Devices Security", evidenceSource: ["MDM Logs / NAC Logs"], remediationGuidance: "Review and remediate 2-5 Mobile Devices Security. See: 2-5 Mobile Devices Security" },
  { id: "CCC-19", pillar: "Applications and Workloads", severity: "medium", standards: ["CCC"], title: "2-5 Mobile Devices Security", description: "Compliance control: 2-5 Mobile Devices Security", evidenceSource: ["MDM Logs / Authentication Logs"], remediationGuidance: "Review and remediate 2-5 Mobile Devices Security. See: 2-5 Mobile Devices Security" },
  { id: "CCC-20", pillar: "Applications and Workloads", severity: "medium", standards: ["CCC"], title: "2-5 Mobile Devices Security", description: "Compliance control: 2-5 Mobile Devices Security", evidenceSource: ["MDM Policy Compliance Reports"], remediationGuidance: "Review and remediate 2-5 Mobile Devices Security. See: 2-5 Mobile Devices Security" },
  { id: "CCC-21", pillar: "Data", severity: "critical", standards: ["CCC"], title: "2-6 Data and Information Protection", description: "Compliance control: 2-6 Data and Information Protection", evidenceSource: ["DB Schema / Data Scanners"], remediationGuidance: "Review and remediate 2-6 Data and Information Protection. See: 2-6 Data and Information Protection" },
  { id: "CCC-22", pillar: "Data", severity: "high", standards: ["CCC"], title: "2-6 Data and Information Protection", description: "Compliance control: 2-6 Data and Information Protection", evidenceSource: ["Contract Management System / Data Disposal Logs"], remediationGuidance: "Review and remediate 2-6 Data and Information Protection. See: 2-6 Data and Information Protection" },
  { id: "CCC-23", pillar: "Data", severity: "high", standards: ["CCC"], title: "2-7 Cryptography", description: "Compliance control: 2-7 Cryptography", evidenceSource: ["TLS Config / Vulnerability Scanners"], remediationGuidance: "Review and remediate 2-7 Cryptography. See: 2-7 Cryptography" },
  { id: "CCC-24", pillar: "Data", severity: "high", standards: ["CCC"], title: "2-7 Cryptography", description: "Compliance control: 2-7 Cryptography", evidenceSource: ["Network Traffic Analysis"], remediationGuidance: "Review and remediate 2-7 Cryptography. See: 2-7 Cryptography" },
  { id: "CCC-25", pillar: "Data", severity: "medium", standards: ["CCC"], title: "2-7 Cryptography", description: "Compliance control: 2-7 Cryptography", evidenceSource: ["Certificate Scanners / TLS Endpoint Probes"], remediationGuidance: "Review and remediate 2-7 Cryptography. See: 2-7 Cryptography" },
  { id: "CCC-26", pillar: "Data", severity: "medium", standards: ["CCC"], title: "2-7 Cryptography", description: "Compliance control: 2-7 Cryptography", evidenceSource: ["Cloud Provider Config"], remediationGuidance: "Review and remediate 2-7 Cryptography. See: 2-7 Cryptography" },
  { id: "CCC-27", pillar: "Visibility & Analytics", severity: "medium", standards: ["CCC"], title: "2-8 Backup and Recovery Management", description: "Compliance control: 2-8 Backup and Recovery Management", evidenceSource: ["Cloud Storage Config / Backup Service Config"], remediationGuidance: "Review and remediate 2-8 Backup and Recovery Management. See: 2-8 Backup and Recovery Management" },
  { id: "CCC-28", pillar: "Visibility & Analytics", severity: "medium", standards: ["CCC"], title: "2-8 Backup and Recovery Management", description: "Compliance control: 2-8 Backup and Recovery Management", evidenceSource: ["Cloud Storage Config / Backup Service Config"], remediationGuidance: "Review and remediate 2-8 Backup and Recovery Management. See: 2-8 Backup and Recovery Management" },
  { id: "CCC-29", pillar: "Networks", severity: "critical", standards: ["CCC"], title: "2-9 Vulnerabilities Management", description: "Compliance control: 2-9 Vulnerabilities Management", evidenceSource: ["Vulnerability Scanner Reports"], remediationGuidance: "Review and remediate 2-9 Vulnerabilities Management. See: 2-9 Vulnerabilities Management" },
  { id: "CCC-30", pillar: "Networks", severity: "critical", standards: ["CCC"], title: "2-9 Vulnerabilities Management", description: "Compliance control: 2-9 Vulnerabilities Management", evidenceSource: ["Vulnerability Scanner Reports"], remediationGuidance: "Review and remediate 2-9 Vulnerabilities Management. See: 2-9 Vulnerabilities Management" },
  { id: "CCC-32", pillar: "Visibility & Analytics", severity: "high", standards: ["CCC"], title: "2-11 Cybersecurity Event Logs and Monitoring Management", description: "Compliance control: 2-11 Cybersecurity Event Logs and Monitoring Management", evidenceSource: ["Cloud Provider Config"], remediationGuidance: "Review and remediate 2-11 Cybersecurity Event Logs and Monitoring Management. See: 2-11 Cybersecurity Event Logs and Monitoring Management" },
  { id: "CCC-33", pillar: "Visibility & Analytics", severity: "high", standards: ["CCC"], title: "2-11 Cybersecurity Event Logs and Monitoring Management", description: "Compliance control: 2-11 Cybersecurity Event Logs and Monitoring Management", evidenceSource: ["System / App Config"], remediationGuidance: "Review and remediate 2-11 Cybersecurity Event Logs and Monitoring Management. See: 2-11 Cybersecurity Event Logs and Monitoring Management" },
  { id: "CCC-34", pillar: "Visibility & Analytics", severity: "medium", standards: ["CCC"], title: "2-11 Cybersecurity Event Logs and Monitoring Management", description: "Compliance control: 2-11 Cybersecurity Event Logs and Monitoring Management", evidenceSource: ["Cloud Provider Config"], remediationGuidance: "Review and remediate 2-11 Cybersecurity Event Logs and Monitoring Management. See: 2-11 Cybersecurity Event Logs and Monitoring Management" },
  { id: "CCC-35", pillar: "Visibility & Analytics", severity: "medium", standards: ["CCC"], title: "2-11 Cybersecurity Event Logs and Monitoring Management", description: "Compliance control: 2-11 Cybersecurity Event Logs and Monitoring Management", evidenceSource: ["SIEM Config / Log Forwarding Config"], remediationGuidance: "Review and remediate 2-11 Cybersecurity Event Logs and Monitoring Management. See: 2-11 Cybersecurity Event Logs and Monitoring Management" },
  { id: "CCC-36", pillar: "Applications and Workloads", severity: "medium", standards: ["CCC"], title: "2-11 Cybersecurity Event Logs and Monitoring Management", description: "Compliance control: 2-11 Cybersecurity Event Logs and Monitoring Management", evidenceSource: ["Audit Logs"], remediationGuidance: "Review and remediate 2-11 Cybersecurity Event Logs and Monitoring Management. See: 2-11 Cybersecurity Event Logs and Monitoring Management" },
  { id: "CCC-37", pillar: "Applications and Workloads", severity: "medium", standards: ["CCC"], title: "2-11 Cybersecurity Event Logs and Monitoring Management", description: "Compliance control: 2-11 Cybersecurity Event Logs and Monitoring Management", evidenceSource: ["Session Manager Logs / VPN Logs"], remediationGuidance: "Review and remediate 2-11 Cybersecurity Event Logs and Monitoring Management. See: 2-11 Cybersecurity Event Logs and Monitoring Management" },
  { id: "CCC-38", pillar: "Applications and Workloads", severity: "high", standards: ["CCC"], title: "2-11 Cybersecurity Event Logs and Monitoring Management", description: "Compliance control: 2-11 Cybersecurity Event Logs and Monitoring Management", evidenceSource: ["SIEM / Monitoring Config"], remediationGuidance: "Review and remediate 2-11 Cybersecurity Event Logs and Monitoring Management. See: 2-11 Cybersecurity Event Logs and Monitoring Management" },
  { id: "CCC-40", pillar: "Applications and Workloads", severity: "high", standards: ["CCC"], title: "2-12 Cybersecurity Incident and Threat Management", description: "Compliance control: 2-12 Cybersecurity Incident and Threat Management", evidenceSource: ["Incident Management System"], remediationGuidance: "Review and remediate 2-12 Cybersecurity Incident and Threat Management. See: 2-12 Cybersecurity Incident and Threat Management" },
  { id: "CCC-43", pillar: "Networks", severity: "high", standards: ["CCC"], title: "2-14 Web Application Security", description: "Compliance control: 2-14 Web Application Security", evidenceSource: ["DAST / SAST Scanner Reports"], remediationGuidance: "Review and remediate 2-14 Web Application Security. See: 2-14 Web Application Security" },
  { id: "CCC-44", pillar: "Applications and Workloads", severity: "high", standards: ["CCC"], title: "2-15 Key Management", description: "Compliance control: 2-15 Key Management", evidenceSource: ["Application Config / System Scanners"], remediationGuidance: "Review and remediate 2-15 Key Management. See: 2-15 Key Management" },
  { id: "CCC-45", pillar: "Applications and Workloads", severity: "high", standards: ["CCC"], title: "2-15 Key Management", description: "Compliance control: 2-15 Key Management", evidenceSource: ["KMS Config"], remediationGuidance: "Review and remediate 2-15 Key Management. See: 2-15 Key Management" },
  { id: "CCC-46", pillar: "Applications and Workloads", severity: "medium", standards: ["CCC"], title: "2-15 Key Management", description: "Compliance control: 2-15 Key Management", evidenceSource: ["KMS Config"], remediationGuidance: "Review and remediate 2-15 Key Management. See: 2-15 Key Management" },
  { id: "CCC-47", pillar: "Applications and Workloads", severity: "medium", standards: ["CCC"], title: "2-15 Key Management", description: "Compliance control: 2-15 Key Management", evidenceSource: ["KMS Config / Cloud Provider Logging Config"], remediationGuidance: "Review and remediate 2-15 Key Management. See: 2-15 Key Management" },
  { id: "CCC-48", pillar: "Applications and Workloads", severity: "medium", standards: ["CCC"], title: "2-16 System Development Security", description: "Compliance control: 2-16 System Development Security", evidenceSource: ["Static Code Analysis / Git Scanners"], remediationGuidance: "Review and remediate 2-16 System Development Security. See: 2-16 System Development Security" },
  { id: "CCC-49", pillar: "Applications and Workloads", severity: "medium", standards: ["CCC"], title: "2-16 System Development Security", description: "Compliance control: 2-16 System Development Security", evidenceSource: ["Network Config / DB Config"], remediationGuidance: "Review and remediate 2-16 System Development Security. See: 2-16 System Development Security" },
  { id: "CCC-51", pillar: "Applications and Workloads", severity: "medium", standards: ["CCC"], title: "2-17 Storage Media Security", description: "Compliance control: 2-17 Storage Media Security", evidenceSource: ["Endpoint Security Agent Logs"], remediationGuidance: "Review and remediate 2-17 Storage Media Security. See: 2-17 Storage Media Security" },
  { id: "CCC-31", pillar: "Applications and Workloads", severity: "medium", standards: ["CCC"], title: "2-11 Cybersecurity Event Logs and Monitoring Management", description: "Compliance control: 2-11 Cybersecurity Event Logs and Monitoring Management", evidenceSource: ["Cloud Provider Config / Log Storage Config"], remediationGuidance: "Review and remediate 2-11 Cybersecurity Event Logs and Monitoring Management. See: 2-11 Cybersecurity Event Logs and Monitoring Management" },
  { id: "CCC-39", pillar: "Applications and Workloads", severity: "medium", standards: ["CCC"], title: "2-12 Cybersecurity Incident and Threat Management", description: "Compliance control: 2-12 Cybersecurity Incident and Threat Management", evidenceSource: ["Incident Management System / Audit Records"], remediationGuidance: "Review and remediate 2-12 Cybersecurity Incident and Threat Management. See: 2-12 Cybersecurity Incident and Threat Management" },
  { id: "CCC-41", pillar: "Applications and Workloads", severity: "medium", standards: ["CCC"], title: "2-13 Cybersecurity Vulnerability Management", description: "Compliance control: 2-13 Cybersecurity Vulnerability Management", evidenceSource: ["Patch Management System / Asset Inventory"], remediationGuidance: "Review and remediate 2-13 Cybersecurity Vulnerability Management. See: 2-13 Cybersecurity Vulnerability Management" },
  { id: "CCC-42", pillar: "Applications and Workloads", severity: "medium", standards: ["CCC"], title: "2-13 Cybersecurity Vulnerability Management", description: "Compliance control: 2-13 Cybersecurity Vulnerability Management", evidenceSource: ["Penetration Testing Reports / Remediation Tracker"], remediationGuidance: "Review and remediate 2-13 Cybersecurity Vulnerability Management. See: 2-13 Cybersecurity Vulnerability Management" },
  { id: "CCC-50", pillar: "Applications and Workloads", severity: "medium", standards: ["CCC"], title: "2-15 Cybersecurity in IT Project Management", description: "Compliance control: 2-15 Cybersecurity in IT Project Management", evidenceSource: ["CI/CD Pipeline Configuration / Code Review Records"], remediationGuidance: "Review and remediate 2-15 Cybersecurity in IT Project Management. See: 2-15 Cybersecurity in IT Project Management" },
  { id: "TC-15", pillar: "Applications and Workloads", severity: "medium", standards: ["HIPAA", "CCC"], title: "§164.312(b) – Audit Controls", description: "Compliance control: §164.312(b) – Audit Controls", evidenceSource: ["Audit Log Review Records"], remediationGuidance: "Review and remediate §164.312(b) – Audit Controls. See: §164.312(b) – Audit Controls" },
  { id: "TC-16", pillar: "Applications and Workloads", severity: "medium", standards: ["HIPAA", "CCC"], title: "§164.312(c)(1) – Integrity", description: "Compliance control: §164.312(c)(1) – Integrity", evidenceSource: ["System Configuration / Storage Config"], remediationGuidance: "Review and remediate §164.312(c)(1) – Integrity. See: §164.312(c)(1) – Integrity" },
  { id: "TC-17", pillar: "Applications and Workloads", severity: "medium", standards: ["HIPAA", "CCC"], title: "§164.312(e)(2)(ii) – Encryption and Decryption", description: "Compliance control: §164.312(e)(2)(ii) – Encryption and Decryption", evidenceSource: ["Network / Load Balancer Configuration"], remediationGuidance: "Review and remediate §164.312(e)(2)(ii) – Encryption and Decryption. See: §164.312(e)(2)(ii) – Encryption and Decryption" },
  { id: "TC-18", pillar: "Applications and Workloads", severity: "medium", standards: ["HIPAA", "CCC"], title: "§164.400–414 – Breach Notification Rule", description: "Compliance control: §164.400–414 – Breach Notification Rule", evidenceSource: ["SIEM / Alerting Configuration"], remediationGuidance: "Review and remediate §164.400–414 – Breach Notification Rule. See: §164.400–414 – Breach Notification Rule" },
  { id: "SC-25", pillar: "Applications and Workloads", severity: "medium", standards: ["SeHE", "CCC"], title: "Consent and Access Control Policy – §6.4", description: "Compliance control: Consent and Access Control Policy – §6.4", evidenceSource: ["Consent Management System / Access Logs"], remediationGuidance: "Review and remediate Consent and Access Control Policy – §6.4. See: Consent and Access Control Policy – §6.4" },
  { id: "SC-26", pillar: "Applications and Workloads", severity: "medium", standards: ["SeHE", "CCC"], title: "Information Security Policy – §3.2", description: "Compliance control: Information Security Policy – §3.2", evidenceSource: ["Data Flow Diagrams / API Request Logs"], remediationGuidance: "Review and remediate Information Security Policy – §3.2. See: Information Security Policy – §3.2" },
  { id: "SC-27", pillar: "Applications and Workloads", severity: "medium", standards: ["SeHE", "CCC"], title: "Authentication Policy – §5.1", description: "Compliance control: Authentication Policy – §5.1", evidenceSource: ["Access Logs / Authentication Events"], remediationGuidance: "Review and remediate Authentication Policy – §5.1. See: Authentication Policy – §5.1" },
  { id: "SC-28", pillar: "Applications and Workloads", severity: "medium", standards: ["SeHE", "CCC"], title: "System Protection Policy – §7.3", description: "Compliance control: System Protection Policy – §7.3", evidenceSource: ["Container Registry / CI/CD Pipeline Config"], remediationGuidance: "Review and remediate System Protection Policy – §7.3. See: System Protection Policy – §7.3" },
  { id: "SC-29", pillar: "Applications and Workloads", severity: "medium", standards: ["SeHE", "CCC"], title: "Audit Policy – §9.5", description: "Compliance control: Audit Policy – §9.5", evidenceSource: ["HIE Transaction Logs"], remediationGuidance: "Review and remediate Audit Policy – §9.5. See: Audit Policy – §9.5" },
];

// ── Breakdowns ──────────────────────────────────────────────────────────────

export function computeBreakdowns(results: ControlResult[]) {
  const pillarBreakdown: Record<string, { passed: number; failed: number; total: number }> = {};
  const severityBreakdown: Record<string, { passed: number; failed: number; total: number }> = {};
  const standardBreakdown: Record<string, { passed: number; failed: number; total: number }> = {};

  for (const r of results) {
    // Pillar
    if (!pillarBreakdown[r.pillar]) pillarBreakdown[r.pillar] = { passed: 0, failed: 0, total: 0 };
    pillarBreakdown[r.pillar].total++;
    if (r.status === "pass") pillarBreakdown[r.pillar].passed++;
    else if (r.status === "fail") pillarBreakdown[r.pillar].failed++;

    // Severity
    if (!severityBreakdown[r.severity]) severityBreakdown[r.severity] = { passed: 0, failed: 0, total: 0 };
    severityBreakdown[r.severity].total++;
    if (r.status === "pass") severityBreakdown[r.severity].passed++;
    else if (r.status === "fail") severityBreakdown[r.severity].failed++;

    // Standards
    for (const std of r.standards) {
      if (!standardBreakdown[std]) standardBreakdown[std] = { passed: 0, failed: 0, total: 0 };
      standardBreakdown[std].total++;
      if (r.status === "pass") standardBreakdown[std].passed++;
      else if (r.status === "fail") standardBreakdown[std].failed++;
    }
  }

  return { pillarBreakdown, severityBreakdown, standardBreakdown };
}
// ── Mock Results Generator (for demo/testing only) ───────────────────────────

/**
 * Generates mock scan results for demo/testing purposes.
 * @param passRate - fraction of controls that should "pass" (0.0 to 1.0)
 */
export function generateMockResults(passRate = 0.68): ControlResult[] {
  return CONTROLS.map((control) => {
    const pass = Math.random() < passRate;
    return {
      ...control,
      status: pass ? ("pass" as const) : ("fail" as const),
      violations: pass
        ? []
        : [`Mock violation: ${control.title} is not compliant`],
    };
  });
}
