// 84 Zero Trust controls metadata — shared between server and client

export type Pillar =
  | "Identity"
  | "Devices"
  | "Networks"
  | "Applications & Workloads"
  | "Cross-Cutting Capabilities";

export type Severity = "critical" | "high" | "medium" | "low";
export type Standard = "CCC" | "HIPAA" | "SeHE";
export type ControlStatus = "pass" | "fail" | "skipped";

export interface Control {
  id: string;           // e.g. "IDN-001"
  controlId: string;    // e.g. "CCC-2-2-P-1-6"
  pillar: Pillar;
  severity: Severity;
  standards: Standard[];
  title: string;
  description: string;
  evidenceSource: string[];
  remediationGuidance: string;
}

export interface ControlResult extends Control {
  status: ControlStatus;
  violations: string[];
}

export const CONTROLS: Control[] = [
  // ── Identity (13) ──────────────────────────────────────────────────────────
  { id: "IDN-001", controlId: "CCC-2-2-P-1-6",  pillar: "Identity", severity: "medium",   standards: ["CCC","HIPAA"],       title: "IAM Provisioning/Deprovisioning",           description: "User accounts must be provisioned and deprovisioned through a formal process tied to HR events.", evidenceSource: ["tfplan"], remediationGuidance: "Implement automated provisioning workflows triggered by HR system events. Ensure terminated employees are deprovisioned within 24 hours." },
  { id: "IDN-002", controlId: "CCC-2-2-P-1-9",  pillar: "Identity", severity: "critical", standards: ["CCC","HIPAA"],       title: "Privileged Access Management (PAM)",        description: "Privileged access must require approval workflows and be time-limited.", evidenceSource: ["tfplan"], remediationGuidance: "Deploy a PAM solution (e.g., CyberArk, BeyondTrust). Enforce just-in-time access with automatic expiry and approval gates." },
  { id: "IDN-003", controlId: "CCC-2-2-T-1-2",  pillar: "Identity", severity: "medium",   standards: ["CCC"],               title: "Identity Federation / SSO",                description: "Systems must federate identity via a central IdP using SAML 2.0 or OIDC.", evidenceSource: ["tfplan"], remediationGuidance: "Configure SAML 2.0 or OIDC federation with your central IdP. Disable local authentication for federated users." },
  { id: "IDN-004", controlId: "CCC-2-2-P-1-7",  pillar: "Identity", severity: "critical", standards: ["CCC","HIPAA"],       title: "RBAC/ABAC + MFA",                          description: "Role-based or attribute-based access control must be enforced alongside MFA for all users.", evidenceSource: ["tfplan"], remediationGuidance: "Define role hierarchy in IAM. Enforce MFA via conditional access policies. Audit role assignments quarterly." },
  { id: "IDN-005", controlId: "CCC-2-2-P-1-11", pillar: "Identity", severity: "critical", standards: ["CCC","HIPAA"],       title: "MFA Authentication Strength",              description: "Multi-factor authentication must be enforced for all privileged and remote access.", evidenceSource: ["tfplan"], remediationGuidance: "Enable MFA for all accounts. Use TOTP or hardware tokens. Disable SMS-based MFA for privileged accounts." },
  { id: "IDN-006", controlId: "CCC-2-2-P-1-8",  pillar: "Identity", severity: "medium",   standards: ["CCC","SeHE"],        title: "Least Privilege Enforcement",              description: "Users must be granted only the minimum permissions required for their role.", evidenceSource: ["tfplan"], remediationGuidance: "Audit all IAM policies. Remove wildcard (*) permissions. Implement permission boundaries on all roles." },
  { id: "IDN-007", controlId: "CCC-2-2-T-1-3",  pillar: "Identity", severity: "medium",   standards: ["CCC","HIPAA","SeHE"], title: "Session Management & Timeout",             description: "Inactive sessions must be terminated after a defined timeout period.", evidenceSource: ["runtime"], remediationGuidance: "Configure session timeout to 15 minutes for privileged sessions and 30 minutes for standard sessions." },
  { id: "IDN-008", controlId: "CCC-2-2-P-1-10", pillar: "Identity", severity: "medium",   standards: ["CCC"],               title: "Service Account Management",               description: "Service accounts must be inventoried, have minimal permissions, and rotate credentials regularly.", evidenceSource: ["tfplan"], remediationGuidance: "Inventory all service accounts. Implement automatic credential rotation every 90 days. Remove unused service accounts." },
  { id: "IDN-009", controlId: "CCC-2-2-T-1-4",  pillar: "Identity", severity: "medium",   standards: ["CCC","HIPAA"],       title: "Shared Account Prohibition",               description: "Shared or generic accounts (admin, root, guest) must not be used for regular operations.", evidenceSource: ["runtime"], remediationGuidance: "Disable shared accounts. Create individual named accounts for each user. Audit login events for shared account usage." },
  { id: "IDN-010", controlId: "CCC-2-2-P-1-12", pillar: "Identity", severity: "medium",   standards: ["CCC","SeHE"],        title: "Access Review & Recertification",          description: "Access rights must be reviewed and recertified at least quarterly.", evidenceSource: ["tfplan"], remediationGuidance: "Implement quarterly access review campaigns. Revoke access that is not recertified within the review period." },
  { id: "IDN-011", controlId: "CCC-2-2-P-1-13", pillar: "Identity", severity: "medium",   standards: ["CCC","HIPAA"],       title: "Emergency Access (Break-Glass)",           description: "Emergency access procedures must be documented and audited.", evidenceSource: ["runtime"], remediationGuidance: "Define break-glass procedures. Seal emergency credentials in a vault. Alert security team on every use." },
  { id: "IDN-012", controlId: "CCC-2-2-T-1-5",  pillar: "Identity", severity: "medium",   standards: ["SeHE"],              title: "Patient Consent for Data Access",          description: "Access to patient data must be tied to valid, active consent records.", evidenceSource: ["runtime"], remediationGuidance: "Integrate consent management system with access control layer. Block data access when consent is revoked or expired." },
  { id: "IDN-013", controlId: "CCC-2-2-P-1-14", pillar: "Identity", severity: "medium",   standards: ["HIPAA","SeHE"],      title: "Workforce Identity Verification",          description: "Healthcare workforce identity must be verified before granting system access.", evidenceSource: ["tfplan"], remediationGuidance: "Implement identity proofing for all new hires. Integrate with HR system for real-time employment status checks." },

  // ── Devices (13) ───────────────────────────────────────────────────────────
  { id: "DEV-001", controlId: "CCC-2-3-P-1-1",  pillar: "Devices",  severity: "medium",   standards: ["CCC"],               title: "Device Inventory & Asset Management",      description: "All devices accessing the system must be inventoried in a CMDB.", evidenceSource: ["tfplan"], remediationGuidance: "Deploy an asset discovery tool. Maintain a CMDB with all device attributes. Block unregistered devices." },
  { id: "DEV-002", controlId: "CCC-2-3-P-1-2",  pillar: "Devices",  severity: "medium",   standards: ["CCC","HIPAA"],       title: "Mobile Device Management (MDM)",           description: "Mobile devices must be enrolled in an MDM solution with compliance policies enforced.", evidenceSource: ["runtime"], remediationGuidance: "Enroll all mobile devices in MDM (Intune, Jamf). Enforce encryption, screen lock, and remote wipe capabilities." },
  { id: "DEV-003", controlId: "CCC-2-3-P-1-3",  pillar: "Devices",  severity: "high",     standards: ["CCC"],               title: "Endpoint Detection & Response (EDR)",      description: "All endpoints must have EDR agents installed and reporting to a central console.", evidenceSource: ["runtime"], remediationGuidance: "Deploy EDR solution (CrowdStrike, Defender for Endpoint) on all devices. Ensure 100% coverage and active monitoring." },
  { id: "DEV-004", controlId: "CCC-2-3-P-1-4",  pillar: "Devices",  severity: "medium",   standards: ["CCC"],               title: "Device Compliance Posture Check",          description: "Device compliance posture must be verified before granting network access.", evidenceSource: ["runtime"], remediationGuidance: "Implement NAC solution. Check device compliance (patch level, AV status) at connection time. Quarantine non-compliant devices." },
  { id: "DEV-005", controlId: "CCC-2-3-T-1-1",  pillar: "Devices",  severity: "medium",   standards: ["CCC","HIPAA"],       title: "Full Disk Encryption",                     description: "All devices storing sensitive data must have full disk encryption enabled.", evidenceSource: ["tfplan"], remediationGuidance: "Enable BitLocker (Windows) or FileVault (macOS) on all endpoints. Verify encryption status via MDM compliance reports." },
  { id: "DEV-006", controlId: "CCC-2-3-P-1-5",  pillar: "Devices",  severity: "medium",   standards: ["CCC"],               title: "Patch Management",                         description: "All devices must be patched within defined SLAs (critical: 24h, high: 7d, medium: 30d).", evidenceSource: ["runtime"], remediationGuidance: "Implement automated patch management. Define and enforce patching SLAs. Report on patch compliance weekly." },
  { id: "DEV-007", controlId: "CCC-2-3-P-1-6",  pillar: "Devices",  severity: "medium",   standards: ["CCC"],               title: "Removable Media Controls",                 description: "Use of removable media must be controlled and logged.", evidenceSource: ["runtime"], remediationGuidance: "Disable USB ports by default via Group Policy. Allow only approved devices via MDM whitelist. Log all removable media events." },
  { id: "DEV-008", controlId: "CCC-2-3-T-1-2",  pillar: "Devices",  severity: "medium",   standards: ["CCC","SeHE"],        title: "Medical Device Security",                  description: "Connected medical devices must be inventoried and have network segmentation applied.", evidenceSource: ["tfplan"], remediationGuidance: "Segment medical devices on dedicated VLANs. Implement device-specific firewall rules. Coordinate with vendors for security patches." },
  { id: "DEV-009", controlId: "CCC-2-3-P-1-7",  pillar: "Devices",  severity: "medium",   standards: ["CCC"],               title: "Secure Boot & Firmware Integrity",         description: "Devices must have Secure Boot enabled and firmware integrity verified.", evidenceSource: ["runtime"], remediationGuidance: "Enable Secure Boot in BIOS/UEFI. Implement TPM-based attestation. Monitor firmware version compliance." },
  { id: "DEV-010", controlId: "CCC-2-3-P-1-8",  pillar: "Devices",  severity: "medium",   standards: ["CCC","HIPAA"],       title: "Remote Wipe Capability",                   description: "Lost or stolen devices must be remotely wipeable.", evidenceSource: ["runtime"], remediationGuidance: "Verify remote wipe capability via MDM for all enrolled devices. Test wipe procedure annually. Document procedure." },
  { id: "DEV-011", controlId: "CCC-2-3-T-1-3",  pillar: "Devices",  severity: "medium",   standards: ["CCC"],               title: "Application Allowlisting",                 description: "Only approved applications must be allowed to execute on managed devices.", evidenceSource: ["runtime"], remediationGuidance: "Implement application allowlisting (AppLocker, WDAC). Maintain an approved application catalog. Block unknown executables." },
  { id: "DEV-012", controlId: "CCC-2-3-P-1-9",  pillar: "Devices",  severity: "medium",   standards: ["CCC"],               title: "Device Certificate-Based Authentication",  description: "Devices must authenticate using certificates rather than passwords.", evidenceSource: ["tfplan"], remediationGuidance: "Deploy device certificates via PKI. Configure 802.1X for network access using device certificates." },
  { id: "DEV-013", controlId: "CCC-2-3-P-1-10", pillar: "Devices",  severity: "medium",   standards: ["CCC","SeHE"],        title: "IoT/OT Device Security Baseline",          description: "IoT and OT devices must meet a defined security baseline.", evidenceSource: ["runtime"], remediationGuidance: "Define IoT security baseline. Change default credentials. Disable unused services. Implement network microsegmentation for IoT devices." },

  // ── Networks (9) ───────────────────────────────────────────────────────────
  { id: "NET-001", controlId: "CCC-2-4-P-1-1",  pillar: "Networks", severity: "high",     standards: ["CCC","HIPAA"],       title: "Network Microsegmentation",                description: "Network must be segmented into zones with least-privilege traffic flows.", evidenceSource: ["tfplan"], remediationGuidance: "Implement microsegmentation using security groups or firewall policies. Define allowed traffic flows. Block all other traffic by default." },
  { id: "NET-002", controlId: "CCC-2-4-P-1-2",  pillar: "Networks", severity: "medium",   standards: ["CCC"],               title: "Encrypted Data in Transit",                description: "All data in transit must be encrypted using TLS 1.2 or higher.", evidenceSource: ["runtime"], remediationGuidance: "Enforce TLS 1.2+ on all endpoints. Disable TLS 1.0, 1.1, and SSL. Use strong cipher suites (AES-256, ECDHE)." },
  { id: "NET-003", controlId: "CCC-2-4-P-1-3",  pillar: "Networks", severity: "medium",   standards: ["CCC","HIPAA"],       title: "Web Application Firewall (WAF)",           description: "Public-facing web applications must be protected by a WAF.", evidenceSource: ["tfplan"], remediationGuidance: "Deploy WAF in blocking mode for all public endpoints. Configure OWASP Top 10 rule sets. Review and tune WAF rules monthly." },
  { id: "NET-004", controlId: "CCC-2-4-T-1-1",  pillar: "Networks", severity: "medium",   standards: ["CCC"],               title: "DDoS Protection",                          description: "Internet-facing services must have DDoS protection enabled.", evidenceSource: ["tfplan"], remediationGuidance: "Enable cloud provider DDoS protection (OCI Shield, AWS Shield). Configure rate limiting. Implement traffic scrubbing." },
  { id: "NET-005", controlId: "CCC-2-4-P-1-4",  pillar: "Networks", severity: "medium",   standards: ["CCC"],               title: "Network Traffic Monitoring",               description: "All network traffic must be monitored and anomalies detected.", evidenceSource: ["runtime"], remediationGuidance: "Deploy network monitoring tools (IDS/IPS). Enable VPC flow logs. Forward logs to SIEM for correlation." },
  { id: "NET-006", controlId: "CCC-2-4-P-1-5",  pillar: "Networks", severity: "medium",   standards: ["CCC","HIPAA"],       title: "Remote Access Security (VPN/ZTNA)",        description: "Remote access must use VPN or Zero Trust Network Access with MFA.", evidenceSource: ["tfplan"], remediationGuidance: "Replace legacy VPN with ZTNA solution. Enforce MFA for all remote connections. Log all remote access sessions." },
  { id: "NET-007", controlId: "CCC-2-4-T-1-2",  pillar: "Networks", severity: "medium",   standards: ["CCC"],               title: "DNS Security (DNSSEC/DoH)",                description: "DNS must be secured to prevent hijacking and spoofing.", evidenceSource: ["tfplan"], remediationGuidance: "Enable DNSSEC for all managed zones. Use DNS filtering to block malicious domains. Implement DoH for client queries." },
  { id: "NET-008", controlId: "CCC-2-4-P-1-6",  pillar: "Networks", severity: "medium",   standards: ["CCC"],               title: "Network Access Control (NAC)",             description: "Network access must be controlled based on device and user identity.", evidenceSource: ["tfplan"], remediationGuidance: "Implement 802.1X NAC. Enforce device compliance checks at network admission. Quarantine non-compliant devices." },
  { id: "NET-009", controlId: "CCC-2-4-P-1-7",  pillar: "Networks", severity: "medium",   standards: ["CCC","SeHE"],        title: "Healthcare Network Segmentation (HIE)",    description: "Health information exchange networks must be isolated from general corporate networks.", evidenceSource: ["tfplan"], remediationGuidance: "Create dedicated network segment for HIE traffic. Implement strict firewall rules. Monitor all cross-segment traffic." },

  // ── Applications & Workloads (10) ──────────────────────────────────────────
  { id: "APP-001", controlId: "CCC-2-5-P-1-1",  pillar: "Applications & Workloads", severity: "high",     standards: ["CCC","HIPAA"],       title: "Vulnerability Management",                 description: "Applications must be scanned for vulnerabilities and critical findings remediated promptly.", evidenceSource: ["checkov","runtime"], remediationGuidance: "Run DAST/SAST scans on every release. Remediate critical vulnerabilities within 24 hours. Track open vulnerabilities in a risk register." },
  { id: "APP-002", controlId: "CCC-2-5-P-1-2",  pillar: "Applications & Workloads", severity: "medium",   standards: ["CCC"],               title: "Secure SDLC",                              description: "Security must be integrated into the software development lifecycle.", evidenceSource: ["tfplan"], remediationGuidance: "Implement SAST/DAST in CI/CD pipeline. Conduct threat modeling for new features. Perform security code reviews." },
  { id: "APP-003", controlId: "CCC-2-5-T-1-1",  pillar: "Applications & Workloads", severity: "medium",   standards: ["CCC","HIPAA"],       title: "API Security",                             description: "APIs must be authenticated, rate-limited, and protected against OWASP API Top 10.", evidenceSource: ["runtime"], remediationGuidance: "Enforce OAuth 2.0/API keys for all APIs. Implement rate limiting. Deploy API gateway with WAF integration." },
  { id: "APP-004", controlId: "CCC-2-5-P-1-3",  pillar: "Applications & Workloads", severity: "medium",   standards: ["CCC"],               title: "Container Security",                       description: "Container images must be scanned and only approved base images used.", evidenceSource: ["checkov"], remediationGuidance: "Scan container images in CI/CD. Use minimal base images. Implement admission controllers to block non-compliant images." },
  { id: "APP-005", controlId: "CCC-2-5-P-1-4",  pillar: "Applications & Workloads", severity: "medium",   standards: ["CCC"],               title: "Secrets Management",                       description: "Application secrets must be stored in a secrets manager, not hardcoded.", evidenceSource: ["tfplan"], remediationGuidance: "Migrate all secrets to a secrets manager (Vault, OCI Vault). Scan code for hardcoded secrets. Rotate secrets regularly." },
  { id: "APP-006", controlId: "CCC-2-5-T-1-2",  pillar: "Applications & Workloads", severity: "medium",   standards: ["CCC","HIPAA"],       title: "ePHI Data Masking in Non-Production",      description: "Electronic PHI must be masked or anonymized in non-production environments.", evidenceSource: ["runtime"], remediationGuidance: "Implement data masking pipeline for non-production data refresh. Never copy production ePHI to lower environments without masking." },
  { id: "APP-007", controlId: "CCC-2-5-P-1-5",  pillar: "Applications & Workloads", severity: "medium",   standards: ["CCC","SeHE"],        title: "HIS API Authentication Standards",         description: "HIS APIs must enforce OAuth 2.0 or equivalent authentication standards.", evidenceSource: ["runtime"], remediationGuidance: "Implement OAuth 2.0 client credentials flow for system-to-system HIS API access. Enforce token expiry and rotation." },
  { id: "APP-008", controlId: "CCC-2-5-P-1-6",  pillar: "Applications & Workloads", severity: "medium",   standards: ["CCC"],               title: "Application Configuration Hardening",      description: "Applications must be deployed with hardened configurations.", evidenceSource: ["tfplan"], remediationGuidance: "Apply CIS benchmarks for application servers. Disable debug modes in production. Remove default credentials and sample applications." },
  { id: "APP-009", controlId: "CCC-2-5-T-1-3",  pillar: "Applications & Workloads", severity: "medium",   standards: ["CCC","HIPAA"],       title: "Audit Logging for Application Events",     description: "Applications must log all security-relevant events with sufficient detail.", evidenceSource: ["runtime"], remediationGuidance: "Implement structured logging for authentication, authorization, and data access events. Forward logs to central SIEM." },
  { id: "APP-010", controlId: "CCC-2-5-P-1-7",  pillar: "Applications & Workloads", severity: "medium",   standards: ["CCC","SeHE"],        title: "Interoperability Security (FHIR/HL7)",     description: "Healthcare interoperability interfaces must implement security controls.", evidenceSource: ["runtime"], remediationGuidance: "Secure FHIR/HL7 interfaces with TLS and OAuth 2.0 SMART on FHIR. Validate all incoming messages. Log all interface transactions." },

  // ── Cross-Cutting Capabilities (10) ────────────────────────────────────────
  { id: "CCC-001", controlId: "CCC-2-6-P-1-1",  pillar: "Cross-Cutting Capabilities", severity: "high",     standards: ["CCC","HIPAA"],       title: "Security Information & Event Management (SIEM)", description: "A SIEM must be deployed and collecting logs from all critical systems.", evidenceSource: ["runtime"], remediationGuidance: "Deploy SIEM solution. Onboard all critical log sources. Define and tune correlation rules for key attack scenarios." },
  { id: "CCC-002", controlId: "CCC-2-6-P-1-2",  pillar: "Cross-Cutting Capabilities", severity: "medium",   standards: ["CCC"],               title: "Encryption Key Management",                description: "Encryption keys must be managed through a dedicated KMS with rotation policies.", evidenceSource: ["tfplan"], remediationGuidance: "Centralize key management in KMS. Enable automatic key rotation (annually for CMKs). Implement key access policies and audit logging." },
  { id: "CCC-003", controlId: "CCC-2-6-P-1-3",  pillar: "Cross-Cutting Capabilities", severity: "medium",   standards: ["CCC","HIPAA"],       title: "Backup & Recovery",                        description: "Critical data must be backed up regularly with tested recovery procedures.", evidenceSource: ["tfplan"], remediationGuidance: "Implement automated backups with 3-2-1 rule. Test recovery procedures quarterly. Encrypt all backups. Store offsite copies." },
  { id: "CCC-004", controlId: "CCC-2-6-T-1-1",  pillar: "Cross-Cutting Capabilities", severity: "medium",   standards: ["CCC"],               title: "Incident Response Plan",                   description: "A documented and tested incident response plan must be in place.", evidenceSource: ["runtime"], remediationGuidance: "Document IR plan covering detection, containment, eradication, and recovery. Conduct tabletop exercises annually. Define escalation paths." },
  { id: "CCC-005", controlId: "CCC-2-6-P-1-4",  pillar: "Cross-Cutting Capabilities", severity: "medium",   standards: ["CCC","HIPAA","SeHE"], title: "Data Classification & Handling",           description: "Data must be classified and handled according to its sensitivity level.", evidenceSource: ["tfplan"], remediationGuidance: "Implement data classification policy with at least 4 levels. Deploy DLP tools. Train staff on data handling procedures." },
  { id: "CCC-006", controlId: "CCC-2-6-P-1-5",  pillar: "Cross-Cutting Capabilities", severity: "medium",   standards: ["CCC","SeHE"],        title: "Privacy Impact Assessment",                description: "Privacy impact assessments must be conducted for new systems processing personal data.", evidenceSource: ["runtime"], remediationGuidance: "Conduct PIA for all new systems. Document data flows. Implement privacy by design principles. Review PIAs annually." },
  { id: "CCC-007", controlId: "CCC-2-6-T-1-2",  pillar: "Cross-Cutting Capabilities", severity: "medium",   standards: ["CCC","HIPAA"],       title: "Breach Notification Procedures",           description: "Breach notification procedures must be documented and compliant with regulations.", evidenceSource: ["runtime"], remediationGuidance: "Document breach notification procedures per HIPAA (60-day) and local regulations. Designate breach response team. Test procedures annually." },
  { id: "CCC-008", controlId: "CCC-2-6-P-1-6",  pillar: "Cross-Cutting Capabilities", severity: "medium",   standards: ["CCC"],               title: "Third-Party Risk Management",              description: "Third-party vendors with system access must be assessed for security risk.", evidenceSource: ["tfplan"], remediationGuidance: "Implement vendor risk assessment process. Require security attestations from vendors. Include security requirements in contracts." },
  { id: "CCC-009", controlId: "CCC-2-6-P-1-7",  pillar: "Cross-Cutting Capabilities", severity: "medium",   standards: ["CCC","HIPAA"],       title: "Security Awareness Training",              description: "All staff must complete security awareness training annually.", evidenceSource: ["runtime"], remediationGuidance: "Implement mandatory annual security awareness training. Include phishing simulations. Track completion rates. Provide role-specific training." },
  { id: "CCC-010", controlId: "CCC-2-6-T-1-3",  pillar: "Cross-Cutting Capabilities", severity: "medium",   standards: ["CCC","SeHE"],        title: "Continuous Compliance Monitoring",         description: "Compliance posture must be continuously monitored and reported.", evidenceSource: ["runtime"], remediationGuidance: "Deploy continuous compliance monitoring tools. Generate automated compliance reports. Define KPIs and track trends over time." },

  // ── Additional controls to reach 84 ────────────────────────────────────────
  { id: "IDN-014", controlId: "CCC-2-2-P-2-1",  pillar: "Identity", severity: "medium",   standards: ["HIPAA","SeHE"],      title: "Role-Based Access for ePHI",               description: "Access to ePHI must be restricted to roles with a clinical or operational need.", evidenceSource: ["runtime"], remediationGuidance: "Define ePHI access roles. Implement need-to-know access controls. Audit ePHI access logs monthly." },
  { id: "IDN-015", controlId: "CCC-2-2-P-2-2",  pillar: "Identity", severity: "medium",   standards: ["SeHE"],              title: "Consent-Driven Data Sharing",              description: "Patient data sharing must be governed by explicit consent records.", evidenceSource: ["runtime"], remediationGuidance: "Integrate consent management API. Block data sharing when consent is absent or revoked. Log all consent decisions." },
  { id: "DEV-014", controlId: "CCC-2-3-P-2-1",  pillar: "Devices",  severity: "medium",   standards: ["CCC"],               title: "Device Hardening Baseline",                description: "All devices must comply with a defined hardening baseline (CIS Benchmark).", evidenceSource: ["runtime"], remediationGuidance: "Apply CIS Level 1 benchmark to all managed devices. Automate compliance checks via configuration management tools." },
  { id: "DEV-015", controlId: "CCC-2-3-P-2-2",  pillar: "Devices",  severity: "medium",   standards: ["CCC","HIPAA"],       title: "Anti-Malware Protection",                  description: "All endpoints must have up-to-date anti-malware protection.", evidenceSource: ["runtime"], remediationGuidance: "Deploy enterprise anti-malware solution. Ensure definitions are updated daily. Monitor for detection events in SIEM." },
  { id: "NET-010", controlId: "CCC-2-4-P-2-1",  pillar: "Networks", severity: "medium",   standards: ["CCC"],               title: "Intrusion Detection/Prevention (IDS/IPS)", description: "Network IDS/IPS must be deployed at critical network boundaries.", evidenceSource: ["tfplan"], remediationGuidance: "Deploy IDS/IPS at internet boundary and between network segments. Tune signatures to reduce false positives. Alert on critical detections." },
  { id: "NET-011", controlId: "CCC-2-4-P-2-2",  pillar: "Networks", severity: "medium",   standards: ["CCC","HIPAA"],       title: "Wireless Network Security",                description: "Wireless networks must use WPA3 and be isolated from wired networks.", evidenceSource: ["tfplan"], remediationGuidance: "Upgrade wireless to WPA3. Separate guest, corporate, and medical device SSIDs. Implement wireless IDS." },
  { id: "APP-011", controlId: "CCC-2-5-P-2-1",  pillar: "Applications & Workloads", severity: "medium",   standards: ["CCC"],               title: "Software Composition Analysis (SCA)",      description: "Open source dependencies must be scanned for known vulnerabilities.", evidenceSource: ["checkov"], remediationGuidance: "Integrate SCA tool (Snyk, OWASP Dependency-Check) in CI/CD. Block builds with critical CVEs. Maintain SBOM." },
  { id: "APP-012", controlId: "CCC-2-5-P-2-2",  pillar: "Applications & Workloads", severity: "medium",   standards: ["CCC","SeHE"],        title: "HL7/FHIR Message Validation",              description: "Healthcare messages must be validated against schemas before processing.", evidenceSource: ["runtime"], remediationGuidance: "Implement message validation at integration engine. Reject malformed messages. Log validation failures for review." },
  { id: "CCC-011", controlId: "CCC-2-6-P-2-1",  pillar: "Cross-Cutting Capabilities", severity: "medium",   standards: ["CCC","HIPAA"],       title: "Audit Log Integrity",                      description: "Audit logs must be tamper-proof and retained for the required period.", evidenceSource: ["runtime"], remediationGuidance: "Enable log immutability (WORM storage). Retain logs for minimum 6 years per HIPAA. Implement log integrity monitoring." },
  { id: "CCC-012", controlId: "CCC-2-6-P-2-2",  pillar: "Cross-Cutting Capabilities", severity: "medium",   standards: ["CCC"],               title: "Change Management Controls",               description: "All changes to production systems must go through a formal change management process.", evidenceSource: ["tfplan"], remediationGuidance: "Implement change advisory board process. Require approval for all production changes. Maintain change log with rollback procedures." },
  { id: "IDN-016", controlId: "CCC-2-2-P-3-1",  pillar: "Identity", severity: "medium",   standards: ["CCC"],               title: "Password Policy Enforcement",              description: "Password policies must enforce complexity, length, and rotation requirements.", evidenceSource: ["tfplan"], remediationGuidance: "Enforce minimum 12-character passwords with complexity. Implement password manager. Check against known-breached password lists." },
  { id: "DEV-016", controlId: "CCC-2-3-P-3-1",  pillar: "Devices",  severity: "medium",   standards: ["CCC"],               title: "Vulnerability Scanning for Endpoints",     description: "Endpoints must be scanned for vulnerabilities at least weekly.", evidenceSource: ["runtime"], remediationGuidance: "Deploy vulnerability scanner (Tenable, Qualys). Schedule weekly scans. Prioritize remediation by CVSS score." },
  { id: "NET-012", controlId: "CCC-2-4-P-3-1",  pillar: "Networks", severity: "medium",   standards: ["CCC"],               title: "Firewall Rule Review",                     description: "Firewall rules must be reviewed and cleaned up at least quarterly.", evidenceSource: ["tfplan"], remediationGuidance: "Conduct quarterly firewall rule reviews. Remove unused rules. Document business justification for all rules." },
  { id: "APP-013", controlId: "CCC-2-5-P-3-1",  pillar: "Applications & Workloads", severity: "medium",   standards: ["CCC","HIPAA"],       title: "Data Retention & Disposal",                description: "Data must be retained per policy and securely disposed when no longer needed.", evidenceSource: ["tfplan"], remediationGuidance: "Define data retention schedules per data type. Implement automated deletion. Use certified data destruction for physical media." },
  { id: "CCC-013", controlId: "CCC-2-6-P-3-1",  pillar: "Cross-Cutting Capabilities", severity: "medium",   standards: ["CCC","HIPAA"],       title: "Business Continuity Planning",             description: "Business continuity plans must be documented and tested annually.", evidenceSource: ["runtime"], remediationGuidance: "Document BCP covering critical systems. Define RTO and RPO. Test BCP annually. Update after major changes." },
  { id: "IDN-017", controlId: "CCC-2-2-P-4-1",  pillar: "Identity", severity: "medium",   standards: ["HIPAA"],             title: "Workforce Clearance Procedure",            description: "Background checks must be conducted for all staff with access to ePHI.", evidenceSource: ["tfplan"], remediationGuidance: "Implement pre-employment background check process. Conduct periodic re-checks for privileged users. Document clearance decisions." },
  { id: "DEV-017", controlId: "CCC-2-3-P-4-1",  pillar: "Devices",  severity: "medium",   standards: ["CCC"],               title: "BYOD Security Policy",                     description: "Personal devices used for work must comply with BYOD security policy.", evidenceSource: ["runtime"], remediationGuidance: "Define BYOD policy. Enroll personal devices in MDM with containerization. Enforce minimum security requirements." },
  { id: "NET-013", controlId: "CCC-2-4-P-4-1",  pillar: "Networks", severity: "medium",   standards: ["CCC"],               title: "Network Vulnerability Assessment",         description: "Network infrastructure must be assessed for vulnerabilities quarterly.", evidenceSource: ["runtime"], remediationGuidance: "Conduct quarterly network vulnerability assessments. Remediate critical findings within 30 days. Track findings in risk register." },
  { id: "APP-014", controlId: "CCC-2-5-P-4-1",  pillar: "Applications & Workloads", severity: "medium",   standards: ["CCC"],               title: "Penetration Testing",                      description: "Applications must undergo penetration testing at least annually.", evidenceSource: ["runtime"], remediationGuidance: "Conduct annual penetration tests by qualified testers. Remediate critical findings immediately. Track all findings to closure." },
  { id: "CCC-014", controlId: "CCC-2-6-P-4-1",  pillar: "Cross-Cutting Capabilities", severity: "medium",   standards: ["CCC","HIPAA"],       title: "Risk Assessment",                          description: "A comprehensive risk assessment must be conducted at least annually.", evidenceSource: ["runtime"], remediationGuidance: "Conduct annual risk assessment covering all systems. Document risk treatment decisions. Track risk register. Report to management." },
  { id: "IDN-018", controlId: "CCC-2-2-P-5-1",  pillar: "Identity", severity: "medium",   standards: ["CCC"],               title: "Zero Trust Identity Verification",         description: "Every access request must be verified regardless of network location.", evidenceSource: ["runtime"], remediationGuidance: "Implement continuous authentication. Verify device health and user identity on every request. Remove implicit trust based on network location." },
  { id: "DEV-018", controlId: "CCC-2-3-P-5-1",  pillar: "Devices",  severity: "medium",   standards: ["CCC"],               title: "Device Trust Score",                        description: "Devices must have a calculated trust score used in access decisions.", evidenceSource: ["runtime"], remediationGuidance: "Implement device trust scoring based on compliance posture, patch level, and behavioral signals. Use score in access policy decisions." },
  { id: "NET-014", controlId: "CCC-2-4-P-5-1",  pillar: "Networks", severity: "medium",   standards: ["CCC"],               title: "Software-Defined Perimeter (SDP)",         description: "Network access must be controlled by a software-defined perimeter.", evidenceSource: ["tfplan"], remediationGuidance: "Implement SDP/ZTNA solution. Authenticate and authorize before granting network access. Eliminate implicit network trust." },
  { id: "APP-015", controlId: "CCC-2-5-P-5-1",  pillar: "Applications & Workloads", severity: "medium",   standards: ["CCC"],               title: "Workload Identity & Attestation",          description: "Workloads must have cryptographic identities and attest their integrity.", evidenceSource: ["tfplan"], remediationGuidance: "Implement workload identity using SPIFFE/SPIRE or cloud provider workload identity. Attest workload integrity at startup." },
  { id: "CCC-015", controlId: "CCC-2-6-P-5-1",  pillar: "Cross-Cutting Capabilities", severity: "medium",   standards: ["CCC"],               title: "Zero Trust Architecture Review",           description: "The Zero Trust architecture must be reviewed and updated annually.", evidenceSource: ["runtime"], remediationGuidance: "Conduct annual ZTA review against NIST SP 800-207. Document architecture decisions. Update roadmap based on gaps identified." },
  { id: "IDN-019", controlId: "CCC-2-2-P-6-1",  pillar: "Identity", severity: "medium",   standards: ["SeHE"],              title: "Healthcare Worker Role Segregation",       description: "Clinical and administrative roles must be segregated in the HIS.", evidenceSource: ["runtime"], remediationGuidance: "Define separate role hierarchies for clinical and administrative users. Prevent role overlap. Audit role assignments quarterly." },
  { id: "DEV-019", controlId: "CCC-2-3-P-6-1",  pillar: "Devices",  severity: "medium",   standards: ["SeHE"],              title: "Clinical Workstation Security",            description: "Clinical workstations must have enhanced security controls due to ePHI access.", evidenceSource: ["runtime"], remediationGuidance: "Apply enhanced hardening to clinical workstations. Implement automatic screen lock after 5 minutes. Enable session recording for privileged access." },
  { id: "NET-015", controlId: "CCC-2-4-P-6-1",  pillar: "Networks", severity: "medium",   standards: ["SeHE"],              title: "Clinical Network Isolation",               description: "Clinical networks must be isolated from administrative and guest networks.", evidenceSource: ["tfplan"], remediationGuidance: "Create dedicated VLAN for clinical systems. Implement strict ACLs between clinical and administrative networks. Monitor cross-segment traffic." },
  { id: "APP-016", controlId: "CCC-2-5-P-6-1",  pillar: "Applications & Workloads", severity: "medium",   standards: ["SeHE"],              title: "HIS Audit Trail Completeness",             description: "The HIS must maintain a complete audit trail of all patient record accesses.", evidenceSource: ["runtime"], remediationGuidance: "Enable comprehensive audit logging in HIS. Log all read, write, and delete operations on patient records. Retain logs per regulatory requirements." },
  { id: "CCC-016", controlId: "CCC-2-6-P-6-1",  pillar: "Cross-Cutting Capabilities", severity: "medium",   standards: ["SeHE"],              title: "Patient Data Sovereignty",                 description: "Patient data must remain within approved geographic boundaries.", evidenceSource: ["tfplan"], remediationGuidance: "Configure data residency policies in cloud provider. Verify data processing locations. Document data flows for compliance evidence." },
  { id: "IDN-020", controlId: "CCC-2-2-P-7-1",  pillar: "Identity", severity: "medium",   standards: ["CCC","HIPAA"],       title: "Access Termination on Separation",         description: "System access must be revoked within 1 hour of employment termination.", evidenceSource: ["runtime"], remediationGuidance: "Automate account deprovisioning triggered by HR termination events. Verify deprovisioning within 1 hour. Audit terminated user access monthly." },
  { id: "DEV-020", controlId: "CCC-2-3-P-7-1",  pillar: "Devices",  severity: "medium",   standards: ["CCC"],               title: "Device Decommissioning",                   description: "Decommissioned devices must have data securely wiped before disposal.", evidenceSource: ["runtime"], remediationGuidance: "Implement device decommissioning procedure with data wiping certification. Use NIST 800-88 compliant wiping. Maintain decommission records." },
  { id: "NET-016", controlId: "CCC-2-4-P-7-1",  pillar: "Networks", severity: "medium",   standards: ["CCC"],               title: "Network Configuration Management",         description: "Network configurations must be version-controlled and change-managed.", evidenceSource: ["tfplan"], remediationGuidance: "Store network configurations in version control. Implement configuration drift detection. Require peer review for all network changes." },
  { id: "APP-017", controlId: "CCC-2-5-P-7-1",  pillar: "Applications & Workloads", severity: "medium",   standards: ["CCC","HIPAA"],       title: "Application Availability & Resilience",   description: "Critical applications must meet defined availability SLAs with failover capabilities.", evidenceSource: ["tfplan"], remediationGuidance: "Implement high availability architecture. Define and test failover procedures. Monitor availability against SLA. Conduct DR drills annually." },
  { id: "CCC-017", controlId: "CCC-2-6-P-7-1",  pillar: "Cross-Cutting Capabilities", severity: "medium",   standards: ["CCC","HIPAA"],       title: "Compliance Reporting",                     description: "Regular compliance reports must be generated and reviewed by management.", evidenceSource: ["runtime"], remediationGuidance: "Generate monthly compliance reports. Present to management quarterly. Track compliance trends. Document management review decisions." },
  { id: "IDN-021", controlId: "CCC-2-2-P-8-1",  pillar: "Identity", severity: "medium",   standards: ["CCC"],               title: "API Key Management",                       description: "API keys must be rotated regularly and stored securely.", evidenceSource: ["tfplan"], remediationGuidance: "Rotate API keys every 90 days. Store in secrets manager. Monitor for exposed keys in code repositories. Revoke compromised keys immediately." },
  { id: "DEV-021", controlId: "CCC-2-3-P-8-1",  pillar: "Devices",  severity: "medium",   standards: ["CCC"],               title: "Privileged Access Workstation (PAW)",      description: "Privileged administrative tasks must be performed from dedicated PAWs.", evidenceSource: ["runtime"], remediationGuidance: "Provision dedicated PAWs for administrative tasks. Restrict internet access from PAWs. Monitor PAW usage for anomalies." },
  { id: "NET-017", controlId: "CCC-2-4-P-8-1",  pillar: "Networks", severity: "medium",   standards: ["CCC"],               title: "BGP Route Security",                       description: "BGP routing must be secured against route hijacking.", evidenceSource: ["tfplan"], remediationGuidance: "Implement RPKI for BGP route origin validation. Monitor for route anomalies. Coordinate with ISP on routing security." },
  { id: "APP-018", controlId: "CCC-2-5-P-8-1",  pillar: "Applications & Workloads", severity: "medium",   standards: ["CCC"],               title: "Immutable Infrastructure",                 description: "Production workloads should use immutable infrastructure patterns.", evidenceSource: ["tfplan"], remediationGuidance: "Implement infrastructure-as-code with immutable deployments. Replace rather than patch running instances. Use golden AMIs/images." },
  { id: "CCC-018", controlId: "CCC-2-6-P-8-1",  pillar: "Cross-Cutting Capabilities", severity: "medium",   standards: ["CCC"],               title: "Supply Chain Security",                    description: "Software supply chain must be secured against tampering.", evidenceSource: ["tfplan"], remediationGuidance: "Implement code signing for all artifacts. Verify signatures in deployment pipeline. Maintain SBOM. Monitor for supply chain threats." },
];

// Controls loaded — count reflects the full HealthComply framework
if (process.env.NODE_ENV === 'development') {
  console.info(`[Controls] Loaded ${CONTROLS.length} controls across 5 Zero Trust pillars`);
}

export const PILLARS: Pillar[] = [
  "Identity",
  "Devices",
  "Networks",
  "Applications & Workloads",
  "Cross-Cutting Capabilities",
];

export const PILLAR_COLORS: Record<Pillar, string> = {
  "Identity": "#6366f1",
  "Devices": "#f59e0b",
  "Networks": "#10b981",
  "Applications & Workloads": "#3b82f6",
  "Cross-Cutting Capabilities": "#8b5cf6",
};

export const SEVERITY_COLORS: Record<Severity, string> = {
  critical: "#ef4444",
  high: "#f97316",
  medium: "#eab308",
  low: "#22c55e",
};

export function getControlsByPillar(pillar: Pillar) {
  return CONTROLS.filter((c) => c.pillar === pillar);
}

export function generateMockResults(passRate = 0.72): ControlResult[] {
  return CONTROLS.map((control) => {
    const isPassing = Math.random() < passRate;
    return {
      ...control,
      status: isPassing ? "pass" : "fail",
      violations: isPassing
        ? []
        : [`${control.id} violation: ${control.description.split(".")[0]} not satisfied.`],
    };
  });
}

export function computeBreakdowns(results: ControlResult[]) {
  const pillarBreakdown: Record<string, { pass: number; fail: number; total: number }> = {};
  const severityBreakdown: Record<string, { pass: number; fail: number; total: number }> = {};
  const standardBreakdown: Record<string, { pass: number; fail: number; total: number }> = {};

  for (const r of results) {
    // Pillar
    if (!pillarBreakdown[r.pillar]) pillarBreakdown[r.pillar] = { pass: 0, fail: 0, total: 0 };
    pillarBreakdown[r.pillar].total++;
    if (r.status === "pass") pillarBreakdown[r.pillar].pass++;
    else pillarBreakdown[r.pillar].fail++;

    // Severity
    if (!severityBreakdown[r.severity]) severityBreakdown[r.severity] = { pass: 0, fail: 0, total: 0 };
    severityBreakdown[r.severity].total++;
    if (r.status === "pass") severityBreakdown[r.severity].pass++;
    else severityBreakdown[r.severity].fail++;

    // Standards
    for (const std of r.standards) {
      if (!standardBreakdown[std]) standardBreakdown[std] = { pass: 0, fail: 0, total: 0 };
      standardBreakdown[std].total++;
      if (r.status === "pass") standardBreakdown[std].pass++;
      else standardBreakdown[std].fail++;
    }
  }

  return { pillarBreakdown, severityBreakdown, standardBreakdown };
}
